/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Game State Json
         * @description Gets a game state serialized entities table.
         */
        get: operations["get_game_state_json_api_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Units
         * @description Get all combat units for the player faction.
         */
        post: operations["get_units_api_units_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terrain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Terrain
         * @description Get all terrain tiles for the current game state.
         */
        post: operations["get_terrain_api_terrain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Action Move
         * @description Move a unit and return updated rifle squads.
         */
        post: operations["action_move_api_move_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pivot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Action Pivot
         * @description Pivot a unit and return updated rifle squads.
         */
        post: operations["action_pivot_api_pivot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Action Fire
         * @description Move a unit and return updated rifle squads.
         */
        post: operations["action_fire_api_fire_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assault": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Action Assault
         * @description Move a unit and return updated rifle squads.
         */
        post: operations["action_assault_api_assault_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Logs */
        post: operations["get_logs_api_logs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai-play": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Match */
        post: operations["run_match_api_ai_play_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai-config-waypoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ai Config Waypoints */
        post: operations["ai_config_waypoints_api_ai_config_waypoints_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terrain/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Terrain
         * @description Edit the terrain polygon.
         */
        post: operations["update_terrain_api_terrain_update_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terrain/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Terrain
         * @description Edit the terrain polygon.
         */
        post: operations["add_terrain_api_terrain_add_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terrain/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete Terrain
         * @description Edit the terrain polygon.
         */
        post: operations["delete_terrain_api_terrain_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AiWaypointConfigRequest */
        AiWaypointConfigRequest: {
            faction: components["schemas"]["Faction"];
            /** Points */
            points: components["schemas"]["Vec2"][];
        };
        /** AssaultActionLog */
        AssaultActionLog: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            logType: "AssaultActionLog";
            body: components["schemas"]["AssaultActionRequest"];
            outcome?: components["schemas"]["AssaultOutcomes"] | null;
            reactiveFireOutcome?: components["schemas"]["FireOutcomes"] | null;
            viewState: components["schemas"]["GameViewState"];
        };
        /**
         * AssaultActionRequest
         * @description Request model for a unit's assault action.
         */
        AssaultActionRequest: {
            /**
             * Unitid
             * Format: uuid
             */
            unitId: string;
            /**
             * Targetid
             * Format: uuid
             */
            targetId: string;
        };
        /**
         * AssaultOutcomes
         * @description Defines an assault outcome as fail or success.
         * @enum {string}
         */
        AssaultOutcomes: "FAIL" | "SUCCESS";
        /** Body_action_assault_api_assault_post */
        Body_action_assault_api_assault_post: {
            action: components["schemas"]["AssaultActionRequest"];
            /** State */
            state: string;
        };
        /** Body_action_fire_api_fire_post */
        Body_action_fire_api_fire_post: {
            action: components["schemas"]["FireActionRequest"];
            /** State */
            state: string;
        };
        /** Body_action_move_api_move_post */
        Body_action_move_api_move_post: {
            action: components["schemas"]["MoveActionRequest"];
            /** State */
            state: string;
        };
        /** Body_action_pivot_api_pivot_post */
        Body_action_pivot_api_pivot_post: {
            action: components["schemas"]["PivotActionRequest"];
            /** State */
            state: string;
        };
        /** Body_add_terrain_api_terrain_add_post */
        Body_add_terrain_api_terrain_add_post: {
            /** State */
            state: string;
            terrain: components["schemas"]["TerrainModel"];
        };
        /** Body_ai_config_waypoints_api_ai_config_waypoints_post */
        Body_ai_config_waypoints_api_ai_config_waypoints_post: {
            /** State */
            state: string;
            configRequest: components["schemas"]["AiWaypointConfigRequest"];
        };
        /** Body_update_terrain_api_terrain_update_post */
        Body_update_terrain_api_terrain_update_post: {
            /** State */
            state: string;
            terrain: components["schemas"]["TerrainModel"];
        };
        /**
         * Faction
         * @enum {string}
         */
        Faction: "BLUE" | "RED";
        /** FireActionLog */
        FireActionLog: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            logType: "FireActionLog";
            body: components["schemas"]["FireActionRequest"];
            outcome?: components["schemas"]["FireOutcomes"] | null;
            viewState: components["schemas"]["GameViewState"];
        };
        /**
         * FireActionRequest
         * @description Request model for a unit's fire action.
         */
        FireActionRequest: {
            /**
             * Unitid
             * Format: uuid
             */
            unitId: string;
            /**
             * Targetid
             * Format: uuid
             */
            targetId: string;
        };
        /**
         * FireEffect
         * @description Defines all fire effects.
         * @enum {string}
         */
        FireEffect: "PINNING" | "SUPPRESSING";
        /**
         * FireOutcomes
         * @description Defines all fire outcomes.
         * @enum {string}
         */
        FireOutcomes: "MISS" | "PIN" | "SUPPRESS" | "KILL";
        /**
         * GameViewState
         * @description Simplified view model of the game state.
         */
        GameViewState: {
            objectiveState: components["schemas"]["ObjectiveState"];
            /** Hasinitiative */
            hasInitiative: boolean;
            /** Squads */
            squads: components["schemas"]["SquadModel"][];
        };
        /**
         * GameViewStateResponse
         * @description Response model for actions contains view state and mutated game state.
         */
        GameViewStateResponse: {
            viewState: components["schemas"]["GameViewState"];
            /** Jsonstate */
            jsonState: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MoveActionLog */
        MoveActionLog: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            logType: "MoveActionLog";
            body: components["schemas"]["MoveActionRequest"];
            reactiveFireOutcome?: components["schemas"]["FireOutcomes"] | null;
            viewState: components["schemas"]["GameViewState"];
        };
        /**
         * MoveActionRequest
         * @description Request model for a unit's move action.
         */
        MoveActionRequest: {
            /**
             * Unitid
             * Format: uuid
             */
            unitId: string;
            to: components["schemas"]["Vec2"];
        };
        /**
         * ObjectiveState
         * @enum {string}
         */
        ObjectiveState: "INCOMPLETE" | "COMPLETED" | "FAILED";
        /** PivotActionLog */
        PivotActionLog: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            logType: "PivotActionLog";
            body: components["schemas"]["PivotActionRequest"];
            reactiveFireOutcome?: components["schemas"]["FireOutcomes"] | null;
            viewState: components["schemas"]["GameViewState"];
        };
        /**
         * PivotActionRequest
         * @description Request model for a unit's pivot action.
         */
        PivotActionRequest: {
            /**
             * Unitid
             * Format: uuid
             */
            unitId: string;
            to: components["schemas"]["Vec2"];
        };
        /**
         * SquadModel
         * @description Represents a view of a single squad in the game.
         */
        SquadModel: {
            /**
             * Unitid
             * Format: uuid
             */
            unitId: string;
            position: components["schemas"]["Vec2"];
            /** Degree */
            degree: number;
            status: components["schemas"]["Status"];
            /** Isfriendly */
            isFriendly: boolean;
            /** Firingat */
            firingAt?: [
                string,
                components["schemas"]["FireEffect"]
            ] | null;
        };
        /**
         * Status
         * @enum {string}
         */
        Status: "ACTIVE" | "PINNED" | "SUPPRESSED";
        /**
         * TerrainModel
         * @description Represents a view of terrain feature in the game.
         */
        TerrainModel: {
            /**
             * Terrainid
             * Format: uuid
             */
            terrainId: string;
            position: components["schemas"]["Vec2"];
            /** Degrees */
            degrees: number;
            /** Vertices */
            vertices: components["schemas"]["Vec2"][];
            terrainType: components["schemas"]["Types"];
        };
        /**
         * Types
         * @description Supported terrain types.
         * @enum {string}
         */
        Types: "FOREST" | "ROAD" | "FIELD" | "WATER" | "BUILDING";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Vec2 */
        Vec2: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_game_state_json_api_json_get: {
        parameters: {
            query: {
                sceneNames: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_units_api_units_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameViewState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_terrain_api_terrain_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerrainModel"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    action_move_api_move_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_action_move_api_move_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameViewStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    action_pivot_api_pivot_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_action_pivot_api_pivot_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameViewStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    action_fire_api_fire_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_action_fire_api_fire_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameViewStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    action_assault_api_assault_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_action_assault_api_assault_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameViewStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_logs_api_logs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": (components["schemas"]["MoveActionLog"] | components["schemas"]["PivotActionLog"] | components["schemas"]["FireActionLog"] | components["schemas"]["AssaultActionLog"])[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_match_api_ai_play_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameViewStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_config_waypoints_api_ai_config_waypoints_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_ai_config_waypoints_api_ai_config_waypoints_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameViewStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_terrain_api_terrain_update_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_update_terrain_api_terrain_update_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameViewStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_terrain_api_terrain_add_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_add_terrain_api_terrain_add_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameViewStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_terrain_api_terrain_delete_post: {
        parameters: {
            query: {
                terrainId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameViewStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
