/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/scenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Scenes
         * @description Gets a list of scenes.
         */
        get: operations["get_scenes_api_scenes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenes/json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Game State Json
         * @description Gets a game state serialized entities table.
         */
        get: operations["get_game_state_json_api_scenes_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenes/quick-access/json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Game State Json From Quick Access
         * @description Gets a game state serialized entities table.
         */
        get: operations["get_game_state_json_from_quick_access_api_scenes_quick_access_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenes/view": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get View State
         * @description Get all the scene's view state for the player faction.
         */
        post: operations["get_view_state_api_scenes_view_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenes/inspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get State Inspection
         * @description Get the detailed inspection data of the scene.
         */
        post: operations["get_state_inspection_api_scenes_inspect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get Map
         * @description Get map data from a scene.
         */
        post: operations["get_map_api_map_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/perform": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Perform Action
         * @description Move a unit and return updated rifle squads.
         */
        post: operations["perform_action_api_perform_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Logs */
        post: operations["get_logs_api_logs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai-play": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Match */
        post: operations["run_match_api_ai_play_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ai-config-waypoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ai Config Waypoints */
        post: operations["ai_config_waypoints_api_ai_config_waypoints_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terrain/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Terrain
         * @description Edit the terrain polygon.
         */
        post: operations["update_terrain_api_terrain_update_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terrain/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Terrain
         * @description Edit the terrain polygon.
         */
        post: operations["add_terrain_api_terrain_add_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terrain/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete Terrain
         * @description Edit the terrain polygon.
         */
        post: operations["delete_terrain_api_terrain_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/unit/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete Unit
         * @description Deletes a combat unit.
         */
        post: operations["delete_unit_api_unit_add_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/unit/update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Unit
         * @description Edit the combat unit.
         */
        post: operations["update_unit_api_unit_update_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Action: components["schemas"]["MoveAction"] | components["schemas"]["PivotAction"] | components["schemas"]["FireAction"] | components["schemas"]["AssaultAction"];
        ActionLog: components["schemas"]["MoveActionLog"] | components["schemas"]["PivotActionLog"] | components["schemas"]["FireActionLog"] | components["schemas"]["AssaultActionLog"];
        /**
         * AiMatchResponse
         * @description Response model for AI match contains match result and final game state.
         */
        AiMatchResponse: {
            winner: components["schemas"]["Faction"] | null;
            /** Totalruntimeseconds */
            totalRuntimeSeconds: number;
            /** Actionresults */
            actionResults: components["schemas"]["flanker_ai__ai_system__AiSystem__ActionResult"][];
            /** Jsonstate */
            jsonState: string;
        };
        AiSearchLog: components["schemas"]["MinimaxSearchLog"] | components["schemas"]["MctsSearchLog"] | components["schemas"]["ExpectimaxSearchLog"] | components["schemas"]["RandomHeuristicLog"] | components["schemas"]["RandomSearchLog"];
        /** AiWaypointConfigRequest */
        AiWaypointConfigRequest: {
            faction: components["schemas"]["Faction"];
            /** Points */
            points: components["schemas"]["Vec2"][];
        };
        /**
         * AssaultAction
         * @description Moves a unit toward a target and performs an assault on arrival.
         *     Movement draws reactive fires, which may interrupt the move.
         *     The loser of the assault is killed.
         */
        AssaultAction: {
            /**
             * Unitid
             * Format: uuid
             */
            unitId: string;
            /**
             * Targetid
             * Format: uuid
             */
            targetId: string;
        };
        /** AssaultActionLog */
        AssaultActionLog: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            logType: "AssaultActionLog";
            body: components["schemas"]["AssaultActionRequest"];
            outcome: components["schemas"]["AssaultOutcomes"] | null;
            /** Reactivefireoutcomes */
            reactiveFireOutcomes: components["schemas"]["FireOutcomes"][];
            viewState: components["schemas"]["GameViewState"];
        };
        /**
         * AssaultActionRequest
         * @description Request model for a unit's assault action.
         */
        AssaultActionRequest: {
            /**
             * Actiontype
             * @default AssaultActionRequest
             * @constant
             */
            actionType: "AssaultActionRequest";
            /**
             * Unitid
             * Format: uuid
             */
            unitId: string;
            /**
             * Targetid
             * Format: uuid
             */
            targetId: string;
        };
        /** AssaultActionResult */
        AssaultActionResult: {
            outcome: components["schemas"]["AssaultOutcomes"] | null;
            /** Reactivefireoutcomes */
            reactiveFireOutcomes: components["schemas"]["FireOutcomes"][];
        };
        /**
         * AssaultOutcomes
         * @description Defines an assault outcome as fail or success.
         * @enum {string}
         */
        AssaultOutcomes: "FAIL" | "SUCCESS";
        /** Body_add_terrain_api_terrain_add_post */
        Body_add_terrain_api_terrain_add_post: {
            /** State */
            state: string;
            terrain: components["schemas"]["TerrainModel"];
        };
        /** Body_add_unit_api_unit_add_post */
        Body_add_unit_api_unit_add_post: {
            /** State */
            state: string;
            unit: components["schemas"]["SquadModel"];
        };
        /** Body_ai_config_waypoints_api_ai_config_waypoints_post */
        Body_ai_config_waypoints_api_ai_config_waypoints_post: {
            /** State */
            state: string;
            configRequest: components["schemas"]["AiWaypointConfigRequest"];
        };
        /** Body_delete_unit_api_unit_add_post */
        Body_delete_unit_api_unit_add_post: {
            /** State */
            state: string;
            /**
             * Unit Id
             * Format: uuid
             */
            unit_id: string;
        };
        /** Body_perform_action_api_perform_post */
        Body_perform_action_api_perform_post: {
            /** Action */
            action: components["schemas"]["MoveActionRequest"] | components["schemas"]["PivotActionRequest"] | components["schemas"]["FireActionRequest"] | components["schemas"]["AssaultActionRequest"];
            /** State */
            state: string;
        };
        /** Body_update_terrain_api_terrain_update_post */
        Body_update_terrain_api_terrain_update_post: {
            /** State */
            state: string;
            terrain: components["schemas"]["TerrainModel"];
        };
        /** Body_update_unit_api_unit_update_post */
        Body_update_unit_api_unit_update_post: {
            /** State */
            state: string;
            unit: components["schemas"]["SquadModel"];
        };
        /** ExpectimaxSearchLog */
        ExpectimaxSearchLog: {
            /** Treesize */
            treeSize: number;
        };
        /**
         * Faction
         * @enum {string}
         */
        Faction: "BLUE" | "RED";
        /**
         * FireAction
         * @description Fires at an enemy unit. The target must be within line of sight.
         *     Fire modifies the target's status and creates a persistent fire effect.
         *     A failed fire can lose initiative.
         */
        FireAction: {
            /**
             * Unitid
             * Format: uuid
             */
            unitId: string;
            /**
             * Targetid
             * Format: uuid
             */
            targetId: string;
        };
        /** FireActionLog */
        FireActionLog: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            logType: "FireActionLog";
            body: components["schemas"]["FireActionRequest"];
            outcome: components["schemas"]["FireOutcomes"] | null;
            viewState: components["schemas"]["GameViewState"];
        };
        /**
         * FireActionRequest
         * @description Request model for a unit's fire action.
         */
        FireActionRequest: {
            /**
             * Actiontype
             * @default FireActionRequest
             * @constant
             */
            actionType: "FireActionRequest";
            /**
             * Unitid
             * Format: uuid
             */
            unitId: string;
            /**
             * Targetid
             * Format: uuid
             */
            targetId: string;
        };
        /** FireActionResult */
        FireActionResult: {
            outcome: components["schemas"]["FireOutcomes"] | null;
        };
        /**
         * FireEffect
         * @description Defines all fire effects.
         * @enum {string}
         */
        FireEffect: "PINNING" | "SUPPRESSING";
        /** FireEffectPair */
        FireEffectPair: {
            positionA: components["schemas"]["Vec2"];
            positionB: components["schemas"]["Vec2"];
            fireEffectA: components["schemas"]["FireEffect"] | null;
            fireEffectB: components["schemas"]["FireEffect"] | null;
        };
        /**
         * FireOutcomes
         * @description Defines all fire outcomes.
         * @enum {string}
         */
        FireOutcomes: "MISS" | "PIN" | "SUPPRESS" | "KILL";
        /**
         * GameStateInspection
         * @description Detailed inspection debugging data of the game state.
         */
        GameStateInspection: {
            viewState: components["schemas"]["GameViewState"];
            /** Lospolygons */
            losPolygons: components["schemas"]["LosPolygon"][];
            /** Movecandidates */
            moveCandidates: components["schemas"]["Vec2"][];
        };
        /**
         * GameViewState
         * @description Simplified view model of the game state.
         */
        GameViewState: {
            objectiveState: components["schemas"]["ObjectiveState"];
            /** Hasinitiative */
            hasInitiative: boolean;
            /** Squads */
            squads: components["schemas"]["SquadModel"][];
            /** Fireeffectpairs */
            fireEffectPairs: components["schemas"]["FireEffectPair"][];
        };
        /**
         * GameViewStateResponse
         * @description Response model for actions contains view state and mutated game state.
         */
        GameViewStateResponse: {
            viewState: components["schemas"]["GameViewState"];
            /** Jsonstate */
            jsonState: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LosPolygon */
        LosPolygon: {
            faction: components["schemas"]["Faction"];
            /** Lospolygon */
            losPolygon: components["schemas"]["Vec2"][];
            /** Fovpolygon */
            fovPolygon: components["schemas"]["Vec2"][];
        };
        /**
         * MapViewState
         * @description Simplified view model of the game map.
         */
        MapViewState: {
            /** Terrains */
            terrains: components["schemas"]["TerrainModel"][];
            /** Boundary */
            boundary: components["schemas"]["Vec2"][];
        };
        /** MctsSearchLog */
        MctsSearchLog: {
            /** Treedepth */
            treeDepth: number;
        };
        /** MinimaxSearchLog */
        MinimaxSearchLog: {
            /** Treesize */
            treeSize: number;
        };
        /**
         * MoveAction
         * @description Moves a unit to a destination. This pivots toward the movement path
         *     first. Movement draws reactive fires, which may interrupt the move
         *     and can lose initiative.
         */
        MoveAction: {
            /**
             * Unitid
             * Format: uuid
             */
            unitId: string;
            to: components["schemas"]["Vec2"];
        };
        /** MoveActionLog */
        MoveActionLog: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            logType: "MoveActionLog";
            body: components["schemas"]["MoveActionRequest"];
            /** Reactivefireoutcomes */
            reactiveFireOutcomes: components["schemas"]["FireOutcomes"][];
            viewState: components["schemas"]["GameViewState"];
        };
        /**
         * MoveActionRequest
         * @description Request model for a unit's move action.
         */
        MoveActionRequest: {
            /**
             * Actiontype
             * @default MoveActionRequest
             * @constant
             */
            actionType: "MoveActionRequest";
            /**
             * Unitid
             * Format: uuid
             */
            unitId: string;
            to: components["schemas"]["Vec2"];
        };
        /** MoveActionResult */
        MoveActionResult: {
            /** Moveinterrupted */
            moveInterrupted: boolean;
            /** Reactivefireoutcomes */
            reactiveFireOutcomes: components["schemas"]["FireOutcomes"][];
        };
        /**
         * ObjectiveState
         * @enum {string}
         */
        ObjectiveState: "INCOMPLETE" | "COMPLETED" | "FAILED";
        /**
         * PivotAction
         * @description Pivots a unit toward a destination. Pivoting draws reactive fires
         *     and can lose initiative. Pivoting always complete regardless
         */
        PivotAction: {
            /**
             * Unitid
             * Format: uuid
             */
            unitId: string;
            to: components["schemas"]["Vec2"];
        };
        /** PivotActionLog */
        PivotActionLog: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            logType: "PivotActionLog";
            body: components["schemas"]["PivotActionRequest"];
            /** Reactivefireoutcomes */
            reactiveFireOutcomes: components["schemas"]["FireOutcomes"][];
            viewState: components["schemas"]["GameViewState"];
        };
        /**
         * PivotActionRequest
         * @description Request model for a unit's pivot action.
         */
        PivotActionRequest: {
            /**
             * Actiontype
             * @default PivotActionRequest
             * @constant
             */
            actionType: "PivotActionRequest";
            /**
             * Unitid
             * Format: uuid
             */
            unitId: string;
            to: components["schemas"]["Vec2"];
        };
        /** PivotActionResult */
        PivotActionResult: {
            /** Reactivefireoutcomes */
            reactiveFireOutcomes: components["schemas"]["FireOutcomes"][];
        };
        /** RandomHeuristicLog */
        RandomHeuristicLog: {
            /** Actionslength */
            actionsLength: number;
        };
        /** RandomSearchLog */
        RandomSearchLog: {
            /** Actionslength */
            actionsLength: number;
        };
        /** SceneManifestResponse */
        SceneManifestResponse: {
            /** Quickaccessscenes */
            quickAccessScenes: string[];
            /** Scenenames */
            sceneNames: string[];
        };
        /**
         * SquadModel
         * @description Represents a view of a single squad in the game.
         */
        SquadModel: {
            /**
             * Unitid
             * Format: uuid
             */
            unitId: string;
            position: components["schemas"]["Vec2"];
            /** Degrees */
            degrees: number;
            status: components["schemas"]["Status"];
            /** Isfriendly */
            isFriendly: boolean;
            /** Fovdegrees */
            fovDegrees: number | null;
            /** Firingat */
            firingAt: [
                string,
                components["schemas"]["FireEffect"]
            ] | null;
        };
        /**
         * Status
         * @enum {string}
         */
        Status: "ACTIVE" | "PINNED" | "SUPPRESSED";
        /**
         * TerrainModel
         * @description Represents a view of terrain feature in the game.
         */
        TerrainModel: {
            /**
             * Terrainid
             * Format: uuid
             */
            terrainId: string;
            position: components["schemas"]["Vec2"];
            /** Degrees */
            degrees: number;
            /** Vertices */
            vertices: components["schemas"]["Vec2"][];
            terrainType: components["schemas"]["Types"];
        };
        /**
         * Types
         * @description Supported terrain types.
         * @enum {string}
         */
        Types: "FOREST" | "ROAD" | "FIELD" | "WATER" | "BUILDING";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Vec2
         * @description 2D vector class for basic vector operations
         */
        Vec2: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** ActionResult */
        flanker_ai__ai_system__AiSystem__ActionResult: {
            faction: components["schemas"]["Faction"];
            /** Actionruntimeseconds */
            actionRuntimeSeconds: number;
            action: components["schemas"]["Action"];
            result: components["schemas"]["flanker_core__models__actions__ActionResult"];
            policyLog: components["schemas"]["AiSearchLog"] | null;
        };
        flanker_core__models__actions__ActionResult: components["schemas"]["MoveActionResult"] | components["schemas"]["PivotActionResult"] | components["schemas"]["FireActionResult"] | components["schemas"]["AssaultActionResult"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_scenes_api_scenes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SceneManifestResponse"];
                };
            };
        };
    };
    get_game_state_json_api_scenes_json_get: {
        parameters: {
            query: {
                sceneNames: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_state_json_from_quick_access_api_scenes_quick_access_json_get: {
        parameters: {
            query: {
                quickAccessName: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_view_state_api_scenes_view_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameViewState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_state_inspection_api_scenes_inspect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameStateInspection"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_map_api_map_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapViewState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    perform_action_api_perform_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_perform_action_api_perform_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameViewStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_logs_api_logs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionLog"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_match_api_ai_play_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiMatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_config_waypoints_api_ai_config_waypoints_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_ai_config_waypoints_api_ai_config_waypoints_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameViewStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_terrain_api_terrain_update_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_update_terrain_api_terrain_update_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameViewStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_terrain_api_terrain_add_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_add_terrain_api_terrain_add_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameViewStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_terrain_api_terrain_delete_post: {
        parameters: {
            query: {
                terrainId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameViewStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_unit_api_unit_add_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_delete_unit_api_unit_add_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameViewStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_unit_api_unit_update_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_update_unit_api_unit_update_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameViewStateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
