/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/{sceneName}/{gameId}/save/{newScene}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Game
         * @description Saves a game into a scene.
         */
        post: operations["save_game_api__sceneName___gameId__save__newScene__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{sceneName}/{gameId}/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Units
         * @description Get all combat units for the player faction.
         */
        get: operations["get_units_api__sceneName___gameId__units_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{sceneName}/{gameId}/terrain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Terrain
         * @description Get all terrain tiles for the current game state.
         */
        get: operations["get_terrain_api__sceneName___gameId__terrain_get"];
        /**
         * Update Terrain
         * @description Edit the terrain polygon.
         */
        put: operations["update_terrain_api__sceneName___gameId__terrain_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{sceneName}/{gameId}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Action Move
         * @description Move a unit and return updated rifle squads.
         */
        post: operations["action_move_api__sceneName___gameId__move_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{sceneName}/{gameId}/fire": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Action Fire
         * @description Move a unit and return updated rifle squads.
         */
        post: operations["action_fire_api__sceneName___gameId__fire_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{sceneName}/{gameId}/assault": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Action Assault
         * @description Move a unit and return updated rifle squads.
         */
        post: operations["action_assault_api__sceneName___gameId__assault_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{sceneName}/{gameId}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Logs */
        get: operations["get_logs_api__sceneName___gameId__logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/{sceneName}/{gameId}/ai-play": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ai Play */
        post: operations["ai_play_api__sceneName___gameId__ai_play_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssaultActionLog */
        AssaultActionLog: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            logType: "AssaultActionLog";
            body: components["schemas"]["AssaultActionRequest"];
            result: components["schemas"]["AssaultActionResult"];
            unitState: components["schemas"]["CombatUnitsViewState"];
        };
        /**
         * AssaultActionRequest
         * @description Request model for a unit's assault action.
         */
        AssaultActionRequest: {
            /** Unitid */
            unitId: number;
            /** Targetid */
            targetId: number;
        };
        /** AssaultActionResult */
        AssaultActionResult: {
            outcome?: components["schemas"]["AssaultOutcomes"] | null;
            reactiveFireOutcome?: components["schemas"]["FireOutcomes"] | null;
        };
        /**
         * AssaultOutcomes
         * @description Defines an assault outcome as fail or success.
         * @enum {string}
         */
        AssaultOutcomes: "FAIL" | "SUCCESS";
        /**
         * CombatUnitsViewState
         * @description View state for all combat units in the game.
         */
        CombatUnitsViewState: {
            objectiveState: components["schemas"]["ObjectiveState"];
            /** Hasinitiative */
            hasInitiative: boolean;
            /** Squads */
            squads: components["schemas"]["SquadModel"][];
        };
        /** FireActionLog */
        FireActionLog: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            logType: "FireActionLog";
            body: components["schemas"]["FireActionRequest"];
            result: components["schemas"]["FireActionResult"];
            unitState: components["schemas"]["CombatUnitsViewState"];
        };
        /**
         * FireActionRequest
         * @description Request model for a unit's fire action.
         */
        FireActionRequest: {
            /** Unitid */
            unitId: number;
            /** Targetid */
            targetId: number;
        };
        /** FireActionResult */
        FireActionResult: {
            outcome?: components["schemas"]["FireOutcomes"] | null;
        };
        /**
         * FireOutcomes
         * @description Defines all fire outcomes.
         * @enum {string}
         */
        FireOutcomes: "MISS" | "PIN" | "SUPPRESS" | "KILL";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MoveActionLog */
        MoveActionLog: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            logType: "MoveActionLog";
            body: components["schemas"]["MoveActionRequest"];
            result: components["schemas"]["MoveActionResult"];
            unitState: components["schemas"]["CombatUnitsViewState"];
        };
        /**
         * MoveActionRequest
         * @description Request model for a unit's move action.
         */
        MoveActionRequest: {
            /** Unitid */
            unitId: number;
            to: components["schemas"]["Vec2"];
        };
        /** MoveActionResult */
        MoveActionResult: {
            reactiveFireOutcome?: components["schemas"]["FireOutcomes"] | null;
        };
        /**
         * ObjectiveState
         * @enum {string}
         */
        ObjectiveState: "INCOMPLETE" | "COMPLETED" | "FAILED";
        /**
         * SquadModel
         * @description Represents a view of a single squad in the game.
         */
        SquadModel: {
            /** Unitid */
            unitId: number;
            position: components["schemas"]["Vec2"];
            status: components["schemas"]["Status"];
            /** Isfriendly */
            isFriendly: boolean;
            /** Nofire */
            noFire: boolean;
        };
        /**
         * Status
         * @enum {string}
         */
        Status: "ACTIVE" | "PINNED" | "SUPPRESSED";
        /**
         * TerrainModel
         * @description Represents a view of terrain feature in the game.
         */
        TerrainModel: {
            /** Terrainid */
            terrainId: number;
            position: components["schemas"]["Vec2"];
            /** Degrees */
            degrees: number;
            /** Vertices */
            vertices: components["schemas"]["Vec2"][];
            terrainType: components["schemas"]["Types"];
        };
        /**
         * Types
         * @description Supported terrain types.
         * @enum {string}
         */
        Types: "FOREST" | "ROAD" | "FIELD" | "WATER" | "BUILDING";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Vec2 */
        Vec2: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    save_game_api__sceneName___gameId__save__newScene__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sceneName: string;
                gameId: number;
                newScene: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_units_api__sceneName___gameId__units_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sceneName: string;
                gameId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CombatUnitsViewState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_terrain_api__sceneName___gameId__terrain_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sceneName: string;
                gameId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerrainModel"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_terrain_api__sceneName___gameId__terrain_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sceneName: string;
                gameId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TerrainModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    action_move_api__sceneName___gameId__move_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sceneName: string;
                gameId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CombatUnitsViewState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    action_fire_api__sceneName___gameId__fire_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sceneName: string;
                gameId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FireActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CombatUnitsViewState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    action_assault_api__sceneName___gameId__assault_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sceneName: string;
                gameId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssaultActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CombatUnitsViewState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_logs_api__sceneName___gameId__logs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sceneName: string;
                gameId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": (components["schemas"]["MoveActionLog"] | components["schemas"]["FireActionLog"] | components["schemas"]["AssaultActionLog"])[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_play_api__sceneName___gameId__ai_play_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sceneName: string;
                gameId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
