/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/rifle-squad": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rifle Squads */
        get: operations["get_rifle_squads_api_rifle_squad_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Action Move */
        post: operations["action_move_api_move_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/terrain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Terrain */
        get: operations["get_terrain_api_terrain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MoveActionRequest */
        MoveActionRequest: {
            /** Unit Id */
            unit_id: number;
            to: components["schemas"]["Vec2"];
        };
        /** SquadModel */
        SquadModel: {
            /** Unit Id */
            unit_id: number;
            position: components["schemas"]["Vec2"];
            status: components["schemas"]["Status"];
            /** Is Friendly */
            is_friendly: boolean;
        };
        /**
         * Status
         * @enum {string}
         */
        Status: "ACTIVE" | "PINNED" | "SUPPRESSED";
        /** TerrainModel */
        TerrainModel: {
            /** Feature Id */
            feature_id: number;
            /** Vertices */
            vertices: components["schemas"]["Vec2"][];
            terrain_type: components["schemas"]["Types"];
        };
        /**
         * Types
         * @description Supported terrain types.
         * @enum {string}
         */
        Types: "FOREST" | "ROAD" | "FIELD" | "WATER" | "BUILDING";
        /** UnitState */
        UnitState: {
            /** Has Initiative */
            has_initiative: boolean;
            /** Squads */
            squads: components["schemas"]["SquadModel"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Vec2 */
        Vec2: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_rifle_squads_api_rifle_squad_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitState"];
                };
            };
        };
    };
    action_move_api_move_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveActionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_terrain_api_terrain_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TerrainModel"][];
                };
            };
        };
    };
}
